#pragma once

enum class MetaCommandResult {
    META_COMMAND_UNRECOGNIZED,
    META_COMMAND_SUCCESS,
    META_COMMAND_EXIT,
    META_COMMAND_BTREE_PRINT,
    META_COMMAND_CONST_EXPORT,
};

enum class StatementResult {
    PREPARE_UNRECOGNIZED_STATEMENT,
    PREPARE_SUCCESS,
    PREPARE_SYNTAX_ERROR,
    PREPARE_STRING_TOO_LONG,
    PREPARE_NEGATIVE_ID,
};

enum class StatementType {
    STATEMENT_UNKNOWN,
    STATEMENT_INSERT,
    STATEMENT_SELECT,
    STATEMENT_RANGED_SELECT,
    STATEMENT_UPDATE,
    STATEMENT_DELETE,
};
